// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations and introspection need Supabase's direct connection (5432).
    // The transaction pooler on 6543 cannot run DDL or hold advisory locks, so
    // the app's DATABASE_URL is deliberately not used here — see .env.example.
    url: process.env["DIRECT_URL"],
    // Optional. Point at a throwaway Postgres to let `prisma migrate diff
    // --from-migrations` replay history without touching the real database.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
